name: "LoRaWAN Add-on"
description: "A complete LoRaWAN Network Server with Chirpstack"
version: "0.0.1"
slug: "lorawan"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8080/tcp: 8080